import { assert } from "@std/assert";
import { APP_FACTS } from "../functions/agent-chat/appFacts.ts";

// Round 9 — the app-capability truth-table. Wave-3 of the eval caught the
// assistant denying real features (photo ID, shared homes, frost alerts) and
// inventing fake ones (Zigbee sensors, CSV export). These pin the load-bearing
// truths so a future edit can't silently drop them.

const FACTS = APP_FACTS.join("\n");

Deno.test("app facts — real features are affirmed", () => {
  assert(/identify from a PHOTO with Plant Lens/i.test(FACTS), "photo ID must be affirmed (RB06)");
  assert(/homes can be SHARED/i.test(FACTS) && /per-member permissions/i.test(FACTS), "shared homes must be affirmed (RB15)");
  assert(/FROST and HEATWAVE alerts built in natively/i.test(FACTS), "native frost alerts must be affirmed (RE15)");
  assert(/paste a whole plant list and AI parses it/i.test(FACTS), "bulk add must be affirmed (RE02)");
  // Corrected fact (user report): weather is PER HOME, not per location; a
  // second different-weather site is a separate home. The old wrong claim
  // ("each location has its own weather") must never come back.
  assert(/forecast is PER HOME/i.test(FACTS), "per-home weather must be stated (RE19)");
  assert(/create a SEPARATE HOME/i.test(FACTS) && /multiple homes/i.test(FACTS), "multi-home answer for second sites (RE19)");
  assert(!/EACH with its own weather/i.test(FACTS), "the wrong per-location weather claim must be gone");
  assert(/replace a paper journal/i.test(FACTS), "journal capability must be affirmed (RE01)");
  assert(/Sprout is FREE/i.test(FACTS), "free tier must be affirmed (RB04)");
});

Deno.test("app facts — plant-data provenance is correct (user correction, RE18)", () => {
  assert(/OWN plant library/i.test(FACTS) && /mainly generated by the Gemini AI model/i.test(FACTS), "library provenance must be Gemini-generated");
  assert(/independently verified against sources like Wikipedia and GBIF/i.test(FACTS), "verification pipeline must be stated");
  assert(/Don'?t claim the core library comes from the external APIs/i.test(FACTS), "the Perenual/Verdantly inversion must be banned");
});

Deno.test("app facts — the sensor integration list is closed", () => {
  assert(/Ecowitt, eWeLink, or a DIY HTTP webhook — THOSE THREE ONLY/i.test(FACTS), "sensor list must be exhaustive (RE09)");
  assert(/No Zigbee\/Matter\/HomeKit/i.test(FACTS), "other standards must be explicitly excluded");
});

Deno.test("app facts — non-features are honestly listed", () => {
  assert(/NOT AVAILABLE/i.test(FACTS), "missing the not-available section");
  assert(/CSV\/data export, a public API, and printing do(n'?t| not) exist/i.test(FACTS), "export/API/printing must be denied (RE10/RE12/E34/E43)");
});

Deno.test("app facts — frost automation triggers vs native alerts distinction is kept", () => {
  assert(/rain-forecast and heatwave conditions but NOT frost/i.test(FACTS), "automation trigger limits must be stated (E37)");
});

Deno.test("app facts — never-guess instruction bookends the list", () => {
  assert(/never guess in either direction/i.test(FACTS), "must forbid guessing about capabilities");
});

// ── Deep-audit corrections (docs/plans/… round 9; 6-agent verification pass) ──

Deno.test("app facts — weather effect on tasks is stated precisely (no 'reshapes timing')", () => {
  assert(/auto-complete watering tasks/i.test(FACTS), "rain auto-complete must be stated");
  assert(/does NOT reschedule task due dates/i.test(FACTS), "the reschedule overclaim must be banned");
  assert(!/reshapes timing/i.test(FACTS), "the old 'reshapes timing' phrasing must be gone");
});

Deno.test("app facts — plans do not auto-build shopping lists", () => {
  assert(/adding a plan'?s needs to a list is a manual step/i.test(FACTS), "manual plan→list step must be stated");
  assert(/don'?t claim plans auto-build shopping lists/i.test(FACTS), "the auto-build overclaim must be banned");
  assert(!/with linked shopping lists/i.test(FACTS), "the old 'linked shopping lists' phrasing must be gone");
});

Deno.test("app facts — area conditions are the real fields (no soil type/notes)", () => {
  assert(/growing medium & texture/i.test(FACTS), "growing medium/texture must be stated");
  assert(!/soil type\/notes/i.test(FACTS), "the nonexistent soil type/notes field must be gone");
});

Deno.test("app facts — no roadmap talk (user report: AI implied features were coming soon)", () => {
  assert(/NO ROADMAP TALK/i.test(FACTS), "missing the no-roadmap rule");
  assert(/Never say a missing feature is "coming soon"/i.test(FACTS), "coming-soon promises must be banned");
  assert(/hedge with "yet"/i.test(FACTS), "the yet/at-the-moment hedges must be banned");
  assert(!/don'?t exist yet/i.test(FACTS), "the old 'don't exist yet' phrasing must be gone");
  assert(!/currently a manual step/i.test(FACTS), "the 'currently' hedge must be gone");
});

Deno.test("app facts — Contact Support path is the avatar menu Help section", () => {
  assert(/avatar menu \(top right\) under Help → Contact Support/i.test(FACTS), "correct support path must be stated");
  assert(!/Account menu → Contact Support/i.test(FACTS), "the wrong Account-menu path must be gone");
});

// ── Round-11 sweep (docs/plans/garden-ai-eval-round11-global-sweep.md) ───────

Deno.test("app facts — navigation truths exist and invented paths are banned (RE21/N36/RB19)", () => {
  assert(/NAVIGATION/i.test(FACTS), "missing the navigation section");
  assert(/NEVER invent a menu path/i.test(FACTS), "path invention must be banned");
  assert(/Yield \(its harvest history/i.test(FACTS), "harvest history must point at the Yield tab");
  assert(/there is NO separate "Harvest Log" screen/i.test(FACTS), "the invented Harvest Log screen must be denied");
  assert(/tabs include Alerts/i.test(FACTS), "the Alerts tab location must be stated");
});

Deno.test("app facts — offline support is stated precisely (RB13: only task completion queues)", () => {
  assert(/tasks you complete while offline queue/i.test(FACTS), "task-completion queueing must be stated");
  assert(/other edits and all AI features .*need a connection/i.test(FACTS), "the connection requirement must be stated");
  assert(!/changes queue to sync —/i.test(FACTS), "the broad 'changes queue' overclaim must be gone");
  assert(/Don'?t claim every change queues offline/i.test(FACTS), "the overclaim must be explicitly banned");
});

Deno.test("app facts — trust questions get the grounding explanation (RB20/RE14)", () => {
  assert(/how you know something or whether to trust you/i.test(FACTS), "trust-question trigger must exist");
  assert(/every change is a card THEY confirm/i.test(FACTS), "confirm-card grounding must be stated");
});