import { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import type { GeminiUsage } from "./gemini.ts";

const COST_PER_TOKEN: Record<string, number> = {
  "gemini-3.1-flash-lite": 0.00000015,
  "gemini-2.5-flash-lite": 0.00000015,
  "gemini-3-flash-preview": 0.0000003,
  "gemini-3.1-pro-preview": 0.000003,
};

/**
 * Log a Gemini text/vision call (or an Imagen image generation
 * call) to `ai_usage_log` for the audit page + per-user usage
 * meters.
 *
 * For text/vision: pass `usage` (Gemini metadata) — token counts +
 * derived cost land in the regular columns.
 * For Imagen: pass `imageCount` + `imageCostUsd` — image columns
 * populate, token columns stay 0.
 *
 * `estimated_cost_usd` always sums both legs so the audit total
 * stays accurate without joining anything.
 */
export async function logAiUsage(
  db: SupabaseClient,
  opts: {
    homeId?: string | null;
    userId?: string | null;
    functionName: string;
    action?: string | null;
    usage?: GeminiUsage;
    /** Number of images generated by Imagen in this call. */
    imageCount?: number;
    /** Total Imagen cost for this call (per_image × imageCount). */
    imageCostUsd?: number;
    /** Imagen model identifier — overrides `usage.model` for image-only calls. */
    imagenModel?: string;
  },
): Promise<void> {
  const usage = opts.usage;
  const tokenModel = usage?.model;
  const costPerToken = tokenModel ? (COST_PER_TOKEN[tokenModel] ?? 0.0000003) : 0;
  const tokenCost = usage ? costPerToken * usage.totalTokenCount : 0;
  const imageCost = opts.imageCostUsd ?? 0;

  await db.from("ai_usage_log").insert({
    home_id: opts.homeId ?? null,
    user_id: opts.userId ?? null,
    function_name: opts.functionName,
    action: opts.action ?? null,
    model: tokenModel ?? opts.imagenModel ?? "unknown",
    prompt_tokens:     usage?.promptTokenCount     ?? 0,
    candidates_tokens: usage?.candidatesTokenCount ?? 0,
    total_tokens:      usage?.totalTokenCount      ?? 0,
    image_count:       opts.imageCount ?? 0,
    image_cost_usd:    imageCost,
    estimated_cost_usd: tokenCost + imageCost,
  });
}
