-- Weather-aware automations: add a heat-trigger toggle alongside the existing
-- rain-skip toggle.
--
-- ────────────────────────────────────────────────────────────────────────
-- ⚠️  ORDERING BUG: deferred to catch-up migration
-- ────────────────────────────────────────────────────────────────────────
-- This migration's original body did `ALTER TABLE automations ADD COLUMN
-- trigger_if_hot, heat_threshold_c`. The `automations` table is not created
-- until `20260530000000_automations.sql`, so a fresh chronological
-- `supabase db reset` crashes here with
-- `ERROR: relation "automations" does not exist`.
--
-- The real work has been moved to:
--   `20260710020000_ordering_bug_fixups_v2.sql`
--
-- That catch-up runs after `automations` is created and uses
-- `ADD COLUMN IF NOT EXISTS`, so it is a no-op on databases where this
-- migration was historically applied in commit order.
SELECT 1 WHERE false;
