-- ============================================================
-- HOME SEASONAL PICKS — "What can I grow right now?"
--
-- Per-home, per-ISO-week cache of 4-6 personalised sowing / planting /
-- propagating suggestions for the Today screen + Dashboard card.
--
-- Generated by the `seasonal_picks` action on the plant-doctor edge fn:
--   - Sage+   → Gemini call (cached for the ISO week)
--   - Sprout/ → Deterministic JS picker (still cached so the cron + cards
--     Botanist  paint from a single source)
--
-- Refresh paths:
--   - Lazy on-read (cache miss / new week) — first user to open Today
--     after Monday triggers generation.
--   - Pre-warm cron (Mondays 04:00 UTC) — walks warm homes so morning
--     paints are instant.
--
-- Idempotent — safe to re-run via `supabase migration up`.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.home_seasonal_picks (
  home_id       uuid        NOT NULL REFERENCES public.homes(id) ON DELETE CASCADE,
  week_iso      text        NOT NULL,            -- "2026-W19"
  generated_at  timestamptz NOT NULL DEFAULT now(),
  source        text        NOT NULL DEFAULT 'ai'
    CHECK (source IN ('ai', 'fallback')),
  picks         jsonb       NOT NULL,            -- SeasonalPick[]
  PRIMARY KEY (home_id, week_iso)
);

COMMENT ON TABLE public.home_seasonal_picks IS
  'Per-home weekly cache of "what to grow right now" suggestions. PK on (home_id, week_iso) — one row per home per ISO week. Picks are an array of SeasonalPick objects (see _shared/seasonalPicks.ts).';

CREATE INDEX IF NOT EXISTS idx_home_seasonal_picks_week
  ON public.home_seasonal_picks (week_iso);

-- ============================================================
-- RLS
-- Members of the home can read the cached picks for their home.
-- Writes are service-role only (the edge fn writes during refresh).
-- ============================================================

ALTER TABLE public.home_seasonal_picks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Members can view their seasonal picks" ON public.home_seasonal_picks;
CREATE POLICY "Members can view their seasonal picks"
  ON public.home_seasonal_picks
  FOR SELECT
  TO authenticated
  USING (public.is_home_member(home_id));

-- No INSERT/UPDATE/DELETE policies — service role bypasses RLS for these.
