-- Backfill: split comma-joined elements in plant_library jsonb arrays.
--
-- ────────────────────────────────────────────────────────────────────────
-- ⚠️  ORDERING BUG: deferred to catch-up migration
-- ────────────────────────────────────────────────────────────────────────
-- This migration's original body did `UPDATE plant_library SET ...`. The
-- `plant_library` table is not created until `20260624000900_plant_library.sql`,
-- so a fresh chronological `supabase db reset` crashes here with
-- `ERROR: relation "plant_library" does not exist`.
--
-- The real work has been moved to:
--   `20260710020000_ordering_bug_fixups_v2.sql`
--
-- The backfill is naturally idempotent — its WHERE clause filters to rows
-- that still contain comma-joined elements, so on databases where this
-- migration was historically applied in commit order the catch-up touches
-- zero rows.
SELECT 1 WHERE false;
