-- Make the seed_packets_with_germination VIEW respect the caller's RLS.
--
-- ────────────────────────────────────────────────────────────────────────
-- ⚠️  ORDERING BUG: deferred to catch-up migration
-- ────────────────────────────────────────────────────────────────────────
-- This migration's original body did `ALTER VIEW
-- public.seed_packets_with_germination SET (security_invoker = true)`. The
-- view is not created until `20260624000500_nursery.sql`, so a fresh
-- chronological `supabase db reset` crashes here with
-- `ERROR: relation "public.seed_packets_with_germination" does not exist`.
--
-- The real work has been moved to:
--   `20260710020000_ordering_bug_fixups_v2.sql`
--
-- That catch-up runs after the view exists and uses an `IF EXISTS` guard,
-- so it is a no-op on databases where this migration was historically
-- applied in commit order.
SELECT 1 WHERE false;
