-- Expand tasks_type_check to include types generated by ailment automations.
-- ailmentTaskType() produces: Inspection, Pest Control, Pruning, Fertilizing
-- (Watering and Maintenance were already covered)

alter table "public"."tasks" drop constraint if exists "tasks_type_check";

alter table "public"."tasks"
  add constraint "tasks_type_check" check (
    type = any (array[
      'Planting'::text,
      'Watering'::text,
      'Harvesting'::text,
      'Maintenance'::text,
      'Inspection'::text,
      'Pest Control'::text,
      'Pruning'::text,
      'Fertilizing'::text,
      'Plant'::text,
      'Water'::text,
      'Harvest'::text
    ])
  ) not valid;

alter table "public"."tasks" validate constraint "tasks_type_check";
