-- ─── Garden Brain Phase 2: the Head Gardener briefing ───────────────────────
--
-- One ranked morning brief per home per day, generated by
-- `generate-daily-brief` (04:30 UTC, after the 03:45 adaptive-care reconcile).
-- The payload is DETERMINISTICALLY assembled from existing signals; on
-- Sage/Evergreen the summary is rewritten by Gemini (tier model ladders) —
-- `generated_by` records which path produced the stored row.

CREATE TABLE public.daily_briefs (
  home_id      uuid NOT NULL REFERENCES public.homes(id) ON DELETE CASCADE,
  brief_date   date NOT NULL,
  payload      jsonb NOT NULL,              -- { summary, items[], goodNews[], stats }
  tier         text,                        -- owner tier at generation time
  model        text,                        -- Gemini model used (NULL when deterministic)
  generated_by text NOT NULL DEFAULT 'deterministic'
                 CHECK (generated_by IN ('deterministic','ai')),
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (home_id, brief_date)
);

ALTER TABLE public.daily_briefs ENABLE ROW LEVEL SECURITY;

-- Members read their home's briefs; only the service role writes.
CREATE POLICY daily_briefs_select ON public.daily_briefs
  FOR SELECT USING (
    home_id IN (SELECT home_id FROM public.home_members WHERE user_id = auth.uid())
  );

-- Data API exposure (2026-10 rule).
GRANT SELECT ON TABLE public.daily_briefs TO authenticated;

-- ── Daily cron — 04:30 UTC, after garden-brain-reconcile (03:45). ───────────
create extension if not exists pg_cron;

select cron.schedule(
  'generate-daily-brief-daily',
  '30 4 * * *',
  $$
  select net.http_post(
      url:='https://yiuuzlfhtsxbspdyibam.supabase.co/functions/v1/generate-daily-brief',
      headers:='{"Content-Type": "application/json", "Authorization": "Bearer sb_publishable_HDBdrlKd8HMPHto0E6i5QA_nbIPe-3K"}'::jsonb,
      body:='{}'::jsonb
  );
  $$
);
