-- Plant Library Search Lab — supporting extensions, indexes, RPC functions.
--
-- ────────────────────────────────────────────────────────────────────────
-- ⚠️  ORDERING BUG: deferred to catch-up migration
-- ────────────────────────────────────────────────────────────────────────
-- This migration's original body referenced `plant_library` (the GIN index,
-- the function return types). plant_library is not created until the later
-- migration `20260624000900_plant_library.sql`, which means a fresh
-- chronological `supabase db reset` crashes here with
-- `ERROR: relation "plant_library" does not exist`.
--
-- The real work has been moved to:
--   `20260710020000_ordering_bug_fixups_v2.sql`
--
-- That catch-up runs after every plant_library migration, so on a fresh DB
-- the extension + index + functions land in the correct order. On existing
-- remote/dev databases where this migration was historically applied
-- successfully (migrations were applied in commit order, not chronological),
-- the catch-up is fully idempotent — every operation uses
-- IF NOT EXISTS / OR REPLACE and matches the original behaviour.
--
-- This file remains as a chronological no-op so the migration ledger keeps
-- its existing version row on machines that already have it applied.
SELECT 1 WHERE false;
